services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    environment:
      SERVICE_NAME: 'news-aggregator-api'
      SERVICE_TAGS: 'development'
    ports:
      - "8081:80"
    volumes:
      # - ./news-aggregator-api:/var/www/html
      - /C:/xampp/htdocs/news-aggregator-api:/var/www/html  # Correct Windows-style path
      - ./cacert.pem:/etc/ssl/certs/cacert.pem  
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8082:80"  # Map port 8000 on the host to port 80 in the Nginx container
    volumes:
      # - ./news-aggregator-api:/var/www/html
      - /C:/xampp/htdocs/news-aggregator-api:/var/www/html  # Correct Windows-style path
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount your Nginx config
    networks:
      - laravel
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '8080:80'
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
